syntax = "proto3";

package exchanges_events;

option go_package = "github.com/veska-io/streams-proto;eeventspb";

message ExchangesEvent{
	uint64 event_timestamp = 1;

	string exchange = 2;
	string market = 3;
	string base = 4;
	string quot = 5;

	oneof event {
		PriceEvent price = 6;
		VolumeEvent volume = 7;
		OiEvent oi = 8;
		TradesEvent trades = 9;
		LiquidationsEvent liquidations = 10;
		FundingRateEvent funding_rate = 11;
	}

	uint64 processed_timestamp = 12;
}

message PriceEvent {
	double price_open = 1;
	double price_close = 2;
	double price_high = 3;
	double price_low = 4;
}

message VolumeEvent {
	double volume_base = 1;
	double volume_quot = 2;
	double volume_base_buy_taker = 3;
	double volume_quot_buy_taker = 4;
	double volume_base_sell_taker = 5;
	double volume_quot_sell_taker = 6;
}

message OiEvent {
	double oi_open = 1;
}

message TradesEvent {
	uint64 count = 1;
}

message LiquidationsEvent {
	uint64 liquidations_shorts_count = 1;
	uint64 liquidations_longs_count = 2;
	double liquidations_shorts_base_volume = 3;
	double liquidations_longs_base_volume = 4;
	double liquidations_shorts_quot_volume = 5;
	double liquidations_longs_quot_volume = 6;
}

message FundingRateEvent {
	double funding_rate = 1;
	double funding_price = 2;
}